# Generated by Django 5.0.14 on 2026-09-26 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('maestros', '0004_restringir_eliminacion_transacciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['creado_en'], name='inventario__creado__4511dd_idx'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['producto', 'creado_en'], name='inventario__product_7c4b20_idx'),
        ),
    ]
