# Generated by Django 5.0.14 on 2026-09-26 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_restringir_eliminacion_transacciones'),
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['fecha'], name='recepcion_r_fecha_8febd5_idx'),
        ),
    ]
