# Generated by Django 5.0.14 on 2026-09-26 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
        ('maestros', '0004_restringir_eliminacion_transacciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['fecha'], name='despacho_de_fecha_9eab10_idx'),
        ),
    ]
