# Generated by Django 5.0.14 on 2026-09-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['zona', 'codigo'], 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
